on: [push, pull_request]
name: build
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    if: >
      (( github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login ) &&
        github.event_name == 'pull_request' ) || (github.event_name == 'push' && github.event.commits != '[]' )
    env:
      GO111MODULE: on
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build multus-service-controller
      env:
        GOARCH: ${{ matrix.goarch }}
      run: go build -o multus-service-controller_${{ matrix.goarch }} ./cmd/multus-service-controller

    - name: Build multus-proxy
      env:
        GOARCH: ${{ matrix.goarch }}
      run: go build -o multus-proxy_${{ matrix.goarch }} ./cmd/multus-proxy
