name: push-main
on:
  push:
    branches:
      - main
env:
  image-push-owner: 'k8snetworkplumbingwg'
jobs:
  push-main:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      REPOSITORY: ghcr.io/${{ github.repository }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.repository_owner == 'k8snetworkplumbingwg'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        if: github.repository_owner == 'k8snetworkplumbingwg'
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:snapshot

      - name: Push to GitHub Container Registry (nft image)
        if: github.repository_owner == 'k8snetworkplumbingwg'
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:latest-nft
            ghcr.io/${{ github.repository }}:snapshot-nft
          file: Dockerfile.nft
